### ISSUE TITLE
hcxpcapngtool on WI-FI Pineapple: missing dependencies

### ISSUE THREAD

**Issue by ProtoLuke621** [ZerBea/hcxtools#219] opened 2022-08-28 18:29 UTC
so the WI-FI Pineapple does use opkg and this is the latest version for it --> hcxpcapngtool 6.1.6 (C) 2021 ZeroBeat
where on my arch Linux system it is --> hcxpcapngtool 6.2.7 (C) 2022 ZeroBeat

The command I want to use is
hcxdumptool -i wlan1mon -o dumpfile.cap --active_beacon --disable_deauthentication --disable_client_attacks --enable_status=3

This will not work on the WI-FI Pineapple because it says --> hcxdumptool: unrecognized option:  disable_deauthentication

This is very important as I do not want to be sending bad packets into the area around me I need the latest version on my pineapple. I installed this with opkg 1st

So what I have done to try and have the latest version is git clone it and up until the make command it does not work as I get this error:

make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -Wno-error=deprecated-declarations    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.2.7-38-gae348bd\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
make: cc: No such file or directory
make: *** [Makefile:106: hcxpcapngtool] Error 127

ISSUE 2 --> hcxdumptool -i wlan1mon -o dumpfile.cap --active_beacon --disable_deauthentication --disable_client_attacks --enable_status=3

This command on my arch Linux system shows me live captured PMKID packets but on my WI-FI pineapple it shows every packet captured. I only want to see the live captured PMKID packets and have --disable_deauthentication option both work on my WI-FI pineapple

I know that the --disable_deauthentication option works to because without it my deauthentication detector goes off without this option selected

EDIT: after installing pkg-config openssl and zlib I get new errors with the make install-->

Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
No package 'zlib' found
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
No package 'zlib' found
cc -O3 -Wall -Wextra -Wno-error=deprecated-declarations    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.2.7-38-gae348bd\" -DVERSION_YEAR=\"2022\" -DWANTZLIB
make: cc: No such file or directory
make: *** [Makefile:106: hcxpcapngtool] Error 127

**Comment by ZerBea** [comment] 2022-08-29 07:22
It looks like the missing .pc files are not installed on your system. They are part of the development package of the installed packet.
```
e.g. openssl:
$ find -name openssl.pc 2>/dev/null
./usr/lib/openssl-1.0/pkgconfig/openssl.pc
./usr/lib/pkgconfig/openssl.pc

e.g. zlib
$ find -name zlib.pc 2>/dev/null
./usr/lib/pkgconfig/zlib.pc
```

On an Arch Linux system all headers, binaries and configs  are installed by a single command:
`sudo pacman -S zlib
`
https://archlinux.org/packages/core/x86_64/zlib/
```
    usr/
    usr/include/
    usr/include/zconf.h
    usr/include/zlib.h
    usr/lib/
    usr/lib/libz.a
    usr/lib/libz.so
    usr/lib/libz.so.1
    usr/lib/libz.so.1.2.12
    usr/lib/pkgconfig/
    usr/lib/pkgconfig/zlib.pc
    usr/share/
    usr/share/licenses/
    usr/share/licenses/zlib/
    usr/share/licenses/zlib/LICENSE
    usr/share/man/
    usr/share/man/man3/
    usr/share/man/man3/zlib.3.gz
```

That is not the case on other distributions and not hcxtools/hcxdumptool issue.

I don't understand your issue 2:
`hcxdumptool -i wlan1mon -o dumpfile.cap --active_beacon --disable_deauthentication --disable_client_attacks --enable_status=3
`
Are you running the latest git head of hcxdumptool on the pineaple?
If yes, how have you compiled it, because openssl development files are mandatory.

**Comment by ZerBea** [comment] 2022-08-29 13:15
Closed this issue, because you confirmed the hcxtools and hcxdumptool are working as expected on Arch Linux.
From README.md:
```
* Linux (recommended Arch Linux, but other distros should work, too (no support for other distributions).
* gcc >= 11 recommended (deprecated versions are not supported: https://gcc.gnu.org/)
* libopenssl and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl and curl-dev installed (used by whoismac and wlancap2wpasec)
* libpthread and pthread-dev installed (used by hcxhashcattool)
* pkg-config installed
```

Your Pineapple does not have this requirements.

But you can still ask your questions here.

**Closed by ZerBea** 2022-08-29 13:15 UTC
