### ISSUE TITLE
please help me in this issue 

### ISSUE THREAD

**Issue by taha-112** [ZerBea/hcxtools#328] opened 2024-01-16 18:45 UTC
└─# make install PREFIX=/usr/local                
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
cc -O3 -Wall -Wextra -Wpedantic -std=gnu99    -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c    -DVERSION_TAG=\"6.3.2-44-g624f8f5\" -DVERSION_YEAR=\"2024\" -DWANTZLIB
hcxpcapngtool.c:27:10: fatal error: openssl/core.h: No such file or directory
   27 | #include <openssl/core.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:96: hcxpcapngtool] Error 1

**Comment by ZerBea** [comment] 2024-01-16 19:57
It's a lack of dependencies:
```
pkg-config is not installed
openssl >= 3.0 is not installed
openssl headers >= 3.0 are not installed
```
To avoid this, they need to be installed as mentioned in README.md section "Requirements":
```
* gcc >= 13 recommended (deprecated versions are not supported: https://gcc.gnu.org/)
* libopenssl (>= 3.0) and openssl-dev installed
* librt and librt-dev installed (should be installed by default)
* zlib and zlib-dev installed (for gzip compressed cap/pcap/pcapng files)
* libcurl (>= 7.56) and curl-dev installed (used by whoismac and wlancap2wpasec)
* pkg-config installed
```

You can find out exactly how to do this in your distribution's documentation.

Closed this report, because it is not a bug of hcxtools.

**Closed by ZerBea** 2024-01-16 19:57 UTC
