### ISSUE TITLE
Not converted file

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#245] opened 2023-02-20 02:24 UTC
These files should contain a complete handshake, but they do not seem to be converted

[Not converted.zip](https://github.com/ZerBea/hcxtools/files/10778935/Not.converted.zip)

e.g
0_(650).cap
178	Dec 11, 2016 03:32:55.752649000	1	1
182	Dec 11, 2016 03:32:55.779273000	3	2
183	Dec 11, 2016 03:32:55.781323000	3	2
2137	Dec 11, 2016 03:33:01.034823000	1	1
2145	Dec 11, 2016 03:33:01.045564000	3	2
2146	Dec 11, 2016 03:33:01.050684000	4	2
15857	Dec 11, 2016 03:38:41.987643000	1	1
15865	Dec 11, 2016 03:38:42.-00001000	2	1
15867	Dec 11, 2016 03:38:42.004105000	3	2
15869	Dec 11, 2016 03:38:42.008188000	4	2
15870	Dec 11, 2016 03:38:42.009725000	4	2

**Comment by ZerBea** [comment] 2023-02-20 07:04
First of all: This is not a bug, because hcxpcapngtool is working as expected. So I close this report.

Now the analysis:
0_(650).cap contain only one(!) EAPOL M2 which we could use to calculate a message pair
This frame has an invalid timestamp (-00001). So hcxpacapngtool will not convert it!
`15865	19:38:42,-00001	00:12:34:fd:a3:b1	bc:f6:85:43:a1:d2	EAPOL	155	Key (Message 2 of 4)
`
All EAPOL M4 have a zeroed SNONCE and we can't use them.

Before you open another report, please do the following analysis:

Is the time stamp valid.

do you have a ESSID for the handshake

is AKM = PSK

are the EAPOL messages in row (M1,M2,M3,M4)

do you have a complete MESSAGE PAIR:
M1&M2 or M2&M3 or M1&M4 (only if M4 SNONCE is not zeroed) M3&M4 (only if M4 SNONCE is not zeroed)

does the replaycount match:
M1 and M2 have the same replaycount (x) e.g. replaycount 2
M3 and M4 have the same replaycount (x +1) replaycount 3
Is the time gap between the EAPOL MESSAGES <= hcxpcapngtool default value of 5000ms
```
--eapoltimeout=<digit>             : set EAPOL TIMEOUT (milliseconds)
                                   : default: 5000 ms
```

None, and I really mean none of your dump files meet this conditions.



 


BTW:
The quality of this dump files is more than crappy!

**Closed by ZerBea** 2023-02-20 07:04 UTC

**Comment by LLH-l** [comment] 2023-02-20 12:40
Even if there is a problem with the timestamp, it does not seem to affect the password recovery. Moreover, the m2m3 message pair contains complete data and is in the same time group. As long as the EAPOL is calculated accurately, it is possible to successfully recover the password
Of course, this is just my guess

**Comment by ZerBea** [comment] 2023-02-20 14:10
We are talking about default options. 
Running hcxpcapngtools using default options, only MESSAGEPAIRs are converted that meet standard 802.11 convention. 
To avoid vasting GPU time, damaged or invalid frames are completely ignored.
If you really want to convert them, please take a look at the options. They are designed to be used if the dump file is crappy and you accept to get poor results that will possible waste your GPU time.
We take the first example dump file and lower the restriction:
```
$ hcxpcapngtool --eapoltimeout 10000000 '0_(650).cap' -o test.22000
hcxpcapngtool 6.2.7-102-g78e2f8a reading from 0_(650).cap...
failed to read packet 17515

summary capture file
--------------------
file name................................: 0_(650).cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 10.12.2016 20:32:43
timestamp maximum (GMT)..................: 10.12.2016 21:50:16
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105) very basic format without any additional information about the quality
endianess (capture system)...............: little endian
packets inside...........................: 17515
ESSID (total unique).....................: 1
BEACON (total)...........................: 1
BEACON on 2.4 GHz channel (from IE_TAG)..: 6 
ACTION (total)...........................: 78
PROBEREQUEST (directed)..................: 10
PROBERESPONSE (total)....................: 1006
DEAUTHENTICATION (total).................: 6915
AUTHENTICATION (total)...................: 29
AUTHENTICATION (OPEN SYSTEM).............: 29
ASSOCIATIONREQUEST (total)...............: 2
ASSOCIATIONREQUEST (PSK).................: 2
WPA encrypted............................: 63
EAPOL messages (total)...................: 11
EAPOL RSN messages.......................: 11
EAPOLTIME gap (measured maximum usec)....: 4641214646
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 3
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 4
EAPOL M4 messages (total)................: 3
EAPOL pairs (total)......................: 7
EAPOL pairs (best).......................: 1
EAPOL pairs written to 22000 hash file...: 1 (RC checked)
EAPOL M32E2 (authorized).................: 1
packet read error........................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Information: radiotap header is missing!
Radiotap is a de facto standard for 802.11 frame injection and reception.
The radiotap header format is a mechanism to supply additional information about frames,
from the driver to userspace applications.
https://www.radiotap.org/

Warning: too many deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER,
renew ANONCE and set PMKID to zero.
This could prevent to calculate a valid EAPOL MESSAGE PAIR
or to get a valid PMKID.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.


session summary
---------------
processed cap files...................: 1
```
Now the you got a hash file: 
EAPOL pairs written to 22000 hash file...: 1 (RC checked)

BTW:
"As long as the EAPOL is calculated accurately,"
You can't know that at time of conversion.

"Moreover, the m2m3 message pair contains complete data and is in the same time group"
take a look at option "eapoltimeout" that lower the restriction.

To make that absolutely clear:
By default option, crappy values are ignored completely!

**Comment by ZerBea** [comment] 2023-02-20 14:11
It is not the job of hcxpcapngtool to correct bugs of the dump tool!
```
Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.
```

**Comment by ZerBea** [comment] 2023-02-20 14:24
That is horrible and far, far away from the standard EAPOLTIMEOUT:
EAPOLTIME gap (measured maximum usec)....: 4641214646

**Comment by ZerBea** [comment] 2023-02-20 17:59
If you really want to convert everything from crappy dump files, this is the command line:
`$ hcxpcapngtool --all --eapoltimeout=100000000 --nonce-error-corrections=1024 --ignore-ie --max-essids=100 -o test.hc22000 *.cap`

Doing that on the dump files from above:
```
$ hcxpcapngtool --all --eapoltimeout=100000000 --nonce-error-corrections=1024 --ignore-ie --max-essids=100 -o test.hc22000 *.cap
hcxpcapngtool 6.2.7-102-g78e2f8a reading from 0_(3793).cap...
failed to read packet 13035

summary capture file
--------------------
file name................................: 0_(3793).cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 04.11.2015 19:25:40
timestamp maximum (GMT)..................: 04.11.2015 20:38:27
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105) very basic format without any additional information about the quality
endianess (capture system)...............: little endian
packets inside...........................: 13035
WIRELESS DISTRIBUTION SYSTEM.............: 3
ESSID (total unique).....................: 1
BEACON (total)...........................: 1
BEACON on 2.4 GHz channel (from IE_TAG)..: 11 
ACTION (total)...........................: 9
PROBERESPONSE (total)....................: 60
DEAUTHENTICATION (total).................: 768
AUTHENTICATION (total)...................: 1
AUTHENTICATION (OPEN SYSTEM).............: 1
WPA encrypted............................: 102
WEP encrypted............................: 1
EAPOL messages (total)...................: 3
EAPOL RSN messages.......................: 3
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 1
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
packet read error........................: 1
EAPOL messages (malformed packets).......: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Information: no hashes written to hash files

Information: radiotap header is missing!
Radiotap is a de facto standard for 802.11 frame injection and reception.
The radiotap header format is a mechanism to supply additional information about frames,
from the driver to userspace applications.
https://www.radiotap.org/

Warning: too many deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER,
renew ANONCE and set PMKID to zero.
This could prevent to calculate a valid EAPOL MESSAGE PAIR
or to get a valid PMKID.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Information: missing frames!
This dump file does not contain enough EAPOL M1 frames.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it impossible to calculate nonce-error-correction values.

hcxpcapngtool 6.2.7-102-g78e2f8a reading from 0_(650).cap...
failed to read packet 17515

summary capture file
--------------------
file name................................: 0_(650).cap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 10.12.2016 20:32:43
timestamp maximum (GMT)..................: 10.12.2016 21:50:16
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11 (105) very basic format without any additional information about the quality
endianess (capture system)...............: little endian
packets inside...........................: 17515
ESSID (total unique).....................: 1
BEACON (total)...........................: 1
BEACON on 2.4 GHz channel (from IE_TAG)..: 6 
ACTION (total)...........................: 78
PROBEREQUEST (directed)..................: 10
PROBERESPONSE (total)....................: 1006
DEAUTHENTICATION (total).................: 6915
AUTHENTICATION (total)...................: 29
AUTHENTICATION (OPEN SYSTEM).............: 29
ASSOCIATIONREQUEST (total)...............: 2
ASSOCIATIONREQUEST (PSK).................: 2
WPA encrypted............................: 63
EAPOL messages (total)...................: 11
EAPOL RSN messages.......................: 11
EAPOLTIME gap (measured maximum usec)....: 4641214646
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 3
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 4
EAPOL M4 messages (total)................: 3
EAPOL pairs (total)......................: 7
EAPOL pairs (useful).....................: 7
EAPOL pairs written to 22000 hash file...: 7 (RC checked)
EAPOL M12E2 (challenge)..................: 3
EAPOL M32E2 (authorized).................: 4
packet read error........................: 1

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Information: radiotap header is missing!
Radiotap is a de facto standard for 802.11 frame injection and reception.
The radiotap header format is a mechanism to supply additional information about frames,
from the driver to userspace applications.
https://www.radiotap.org/

Warning: too many deauthentication/disassociation frames detected!
That can cause that an ACCESS POINT change channel, reset EAPOL TIMER,
renew ANONCE and set PMKID to zero.
This could prevent to calculate a valid EAPOL MESSAGE PAIR
or to get a valid PMKID.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.


session summary
---------------
processed cap files...................: 2
```

You'll get a hash file hashcat can work on:
```
$ hashcat -m 22000 --nonce-error-corrections=1024 test.hc22000 3WiFi_WiFiKey.txt
hashcat (v6.2.6-266-g9ec6392c9) starting
...
Session..........: hashcat
Status...........: Running
Hash.Mode........: 22000 (WPA-PBKDF2-PMKID+EAPOL)
Hash.Target......: test.hc22000
Time.Started.....: Mon Feb 20 18:57:45 2023 (12 secs)
Time.Estimated...: Mon Feb 20 19:03:32 2023 (5 mins, 35 secs)
Kernel.Feature...: Pure Kernel
Guess.Base.......: File (3WiFi_WiFiKey.txt)
Guess.Queue......: 1/1 (100.00%)
Speed.#1.........:    29877 H/s (5.83ms) @ Accel:8 Loops:256 Thr:256 Vec:1
Recovered........: 0/3 (0.00%) Digests (total), 0/3 (0.00%) Digests (new)
Progress.........: 344154/10354402 (3.32%)
Rejected.........: 90/344154 (0.03%)
Restore.Point....: 344147/10354402 (3.32%)
Restore.Sub.#1...: Salt:0 Amplifier:0-1 Iteration:1-4
Candidate.Engine.: Device Generator
Candidates.#1....: FEC35FB2E -> 28325272211111
Hardware.Mon.#1..: Temp: 69c Fan: 50% Util:100% Core:1873MHz Mem:5005MHz Bus:16
```

But be warned: You may waste GPU time.

**Comment by LLH-l** [comment] 2023-02-22 02:26
OK, Thanks
Let me briefly describe my personal opinion
In terms of the m2m3 message pair, the message in the same time group can basically be regarded as an effective handshake in theory. Whether their counters match or not, the correct password can be successfully recovered. Of course, the EAPOL needs to be calculated correctly

In particular, there are some conditions that will not affect the successful recovery of the password. It seems unnecessary to use too strict filter conditions, which will lead to ignoring those files that can successfully recover the correct password

For only m1m2 message pairs, need to confirm whether they are valid,
But doesn't seem to have done so

Of course, this is already a very good conversion tool
Thanks you very much

**Comment by ZerBea** [comment] 2023-02-22 06:43
I understand this, but from my point of view
`default values/options == standard`
because would like to get the best (valid) handshake as possible.
increase options and more handshakes will be converted, but quality went down

"In particular, there are some conditions that will not affect the successful recovery of the password."
For sure, they will(!) affect it.
Let me explain it regarding the timestamp and how it is calculated:
We take the function gettimeofday()
`gettimeofday(&tvakt, NULL)`

which store the time into a structure timeval:
```
time_t         tv_sec      seconds
suseconds_t    tv_usec     microseconds
```

Form that structure the timestamp is calculated:
`timestamp = ((u64).tv_sec * 1000000L) + tv_usec;
`
Than it is stored in the dump file
```
epbhdr->timestamp_high = timestamp >> 32;
epbhdr->timestamp_low = (u32)timestamp & 0xffffffff;
```
After reading the dump file we do the same procedure backwards to get the time.

If the u64 value timestamp is faulty we do not use it.

To detect a packet loss it is mandatory the the time stamp is ok.
example
This is the handshake, the AP and the CLIENT see:
19:39:07,891393 M1 rc 1
19:39:07,892417 M2 rc 1
19:39:07,893958 M3 rc 2
19:39:07,897958 M4 rc 2 == end of authentication sequence
But this is the the handshake your dump file see. Due to a packet loss not all handshakes are captured

Now we have an M2 and M3 on which most of the conditions meet, but they do not() belong to the same AUTHENTICATION sequence.
```
19:39:07,892417 M2 rc 1
19:39:07,906236 M3 rc 2
```
M2 is from AUTHENTICATION sequence 1
M3 is from AUTHENTICATION sequence 2

Calculation of a PMK of this MESSAGEPAIR will fail epically.

Now, you can imagine what happens on a timestamp with a negative value (-000001).

**Comment by ZerBea** [comment] 2023-02-22 07:02
To make things more complicated:
Some APs increase the REPLAYCOUNTER to initiate an AUTHENTICATION sequence
Some APs increase last 4 bytes of there ANONCE to initiate an AUTHENTICATION sequence (divided  inti BIG ENDIAN and LITTLE ENDIAN models).
Some APs do both (increase REPLAYCOUNTER and last 4  bytes of ANONCE)
Some APs only use REPLAYCOUNTER value 0 and value 1

https://hashcat.net/forum/thread-6361.html

The only constant in this game is the timestamp.

**Comment by LLH-l** [comment] 2023-04-09 08:38
@ZerBea 
An error occurs in the format of the nanosecond timestamp, which will not affect the recovery of the correct password
but only for nanoseconds

[0_(1).zip](https://github.com/ZerBea/hcxtools/files/11185060/0_.1.zip)
Password:  89440290

**Comment by ZerBea** [comment] 2023-04-09 09:12
hcxpcapngtool show this Warning on the dump file:
```
$ hcxpcapngtool '0_(1).cap'
hcxpcapngtool 6.2.9 reading from 0_(1).cap...
...
Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.
```
because it detected a damaged (negative: -00008) timestamp (which is caused by the dump tool which recorded this cap file).

Wireshark confirm the damaged timestamp:
`2698	07:52:52,-00008	48:d2:24:54:0f:68	bc:46:99:e1:c7:de	EAPOL	155	Key (Message 2 of 4)`

Additional pcapngtool give you an information about the measured EAPOL TIME GAP (which is horrible long due to this bug):
EAPOLTIME gap (measured maximum msec)....: 4327389

hcxpcapngtool will not convert hashes from damaged timestamps by default.

Take the measured value, convert it to microseconds (because the dump file has a time resolution of microseconds ) and use it as option to hcxpcapngtool and the hash will be converted:
```
$ hcxpcapngtool '0_(1).cap' --all --eapoltimeout=4327389000 -o damaged.hc22000hcx
hcxpcapngtool 6.2.9 reading from 0_(1).cap...
...
EAPOL pairs written to 22000 hash file...: 4 (RC checked)
...
```

BTW:
"An error occurs in the format of the nanosecond timestamp."

The dump file is in format "cap/pcap":
```
Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng
```
This limited dump file format does not use a time resolution of nanoseconds.
