### ISSUE TITLE
Maximum of supported interfaces reached

### ISSUE THREAD

**Issue by jayofelony** [ZerBea/hcxtools#329] opened 2024-01-31 10:06 UTC
**GitHub is for bugs and features - not for support**
Questions must be posted in the discussion board https://github.com/ZerBea/hcxdumptool/discussions

**Check the FAQ**
Please review the discussions

**Comment output of the tool, e.g.**
1. $ sudo hcxpcapngtool -v
`hcxpcapngtool 6.3.2-44-g624f8f5 (C) 2024 ZeroBeat`

**Describe the bug**
`maximum of supported interfaces reached: 255`

**To Reproduce**
Comment the entire command line
`sudo hcxpcapngtool /root/handshakes/filename.pcapng `

**Expected behavior**
Is this because I captured to many packets? I am trying to convert [bettercap](https://github.com/jayofelony/bettercap) and [pwnagotchi](https://github.com/jayofelony/pwnagotchi-bookworm) to use pcapng.

**Screenshots**
```
hcxpcapngtool 6.3.2-44-g624f8f5 reading from filename.pcapng...
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255
maximum of supported interfaces reached: 255

summary capture file
--------------------
file name................................: filename.pcapng
version (pcapng).........................: 1.0
operating system.........................: linux
application..............................: gopacket
interface name...........................: wlan0mon
interface vendor.........................: 000000
openSSL version..........................: 1.0
weak candidate...........................: N/A
MAC ACCESS POINT.........................: 000000000000 (incremented on every new client)
MAC CLIENT...............................: 000000000000
REPLAYCOUNT..............................: 0
ANONCE...................................: 0000000000000000000000000000000000000000000000000000000000000000
SNONCE...................................: 0000000000000000000000000000000000000000000000000000000000000000
timestamp minimum (GMT)..................: 31.01.2024 09:48:42
timestamp maximum (GMT)..................: 31.01.2024 10:05:51
duration of the dump tool (minutes)......: 17
used capture interfaces..................: 255
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianness (capture system)..............: little endian
packets inside...........................: 654
frames with correct FCS..................: 654
packets received on 2.4 GHz..............: 654
ESSID (total unique).....................: 4
BEACON (total)...........................: 53
BEACON on 2.4 GHz channel (from IE_TAG)..: 11 
ACTION (total)...........................: 17
PROBEREQUEST (undirected)................: 67
PROBERESPONSE (total)....................: 386
DEAUTHENTICATION (total).................: 12
AUTHENTICATION (total)...................: 2
AUTHENTICATION (OPEN SYSTEM).............: 2
ASSOCIATIONREQUEST (total)...............: 1
ASSOCIATIONREQUEST (PSK).................: 1
EAPOL messages (total)...................: 115
EAPOL RSN messages.......................: 115
EAPOLTIME gap (measured maximum msec)....: 4
EAPOL ANONCE error corrections (NC)......: not detected
REPLAYCOUNT gap (measured maximum).......: 3
EAPOL M1 messages (total)................: 100
EAPOL M2 messages (total)................: 6
EAPOL M3 messages (total)................: 6
EAPOL M4 messages (total)................: 3
EAPOL M4 messages (zeroed NONCE).........: 3
EAPOL pairs (total)......................: 24
EAPOL pairs (best).......................: 3
EAPOL M32E2 (authorized).................: 3
packet read error........................: 346

frequency statistics from radiotap header (frequency: received packets)
-----------------------------------------------------------------------
 2417: 28	 2462: 626	

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing/cleaning tool.

Information: no hashes written to hash files


session summary
---------------
processed pcapng files................: 1
```

**Additional context**
I am trying to narrow this down to something, perhaps you have any ideas?

**Comment by ZerBea** [comment] 2024-01-31 10:16
Yes, the application (gopacket) stored a faulty interface description block and hcxdumptools throw a warning.
application..............................: gopacket
And it looks like it destroys the time stamps, too.

Please add a gopacket pcapng dump file.

BTW:
hcxpcapngtool understand pcapng/pcap and cap format. There is absolutely no need to convert dump files.

**Comment by jayofelony** [comment] 2024-01-31 11:18
Bettercap in its original form saves all captures as pcap, I am trying to get it to save as pcapng by default now.
[Ziggo6611EA8_546751b90ca6.zip](https://github.com/ZerBea/hcxtools/files/14110929/Ziggo6611EA8_546751b90ca6.zip)

This capture doesnt have undirected proberequests, hope that is okay.

**Comment by ZerBea** [comment] 2024-01-31 11:44
Thanks.
That dump file contain faulty timestamps (two packets at the same time is not possible):
$ tshark -r Ziggo6611EA8_546751b90ca6.pcapng -T fields -e frame.number -e frame.time
...
5	Jan 31, 2024 12:14:53.098470317 CET
6	Jan 31, 2024 12:14:53.098470317 CET
7	Jan 31, 2024 12:14:53.100778137 CET
8	Jan 31, 2024 12:14:53.100778137 CET
...

And it contains faulty interface information (Number of interfaces in file: 91):
```
$ capinfos Ziggo6611EA8_546751b90ca6.pcapng

File name:           Ziggo6611EA8_546751b90ca6.pcapng
File type:           Wireshark/... - pcapng
File encapsulation:  IEEE 802.11 plus radiotap radio header
File timestamp precision:  nanoseconds (9)
Packet size limit:   file hdr: (not set)
Number of packets:   96
File size:           41 kB
Data size:           27 kB
Capture duration:    165,605046167 seconds
First packet time:   2024-01-31 12:13:40,221948029
Last packet time:    2024-01-31 12:16:25,826994196
Data byte rate:      164 bytes/s
Data bit rate:       1.315 bits/s
Average packet size: 283,66 bytes
Average packet rate: 0 packets/s
SHA256:              6cb813c8d7bde813cf782e970bbca2e692726dac93c81454bc184e752682d1dc
SHA1:                26d925f632df6fb677bfd5632fda29a620470a03
Strict time order:   False
Section 0:

Capture hardware:    arm64
Capture oper-sys:    linux
Capture application: gopacket
Number of interfaces in file: 91
Interface #0 info:
                     Name = wlan0mon
                     Encapsulation = IEEE 802.11 plus radiotap radio header (23 - ieee-802-11-radiotap)
                     Capture length = 0
                     Time precision = nanoseconds (9)
                     Time ticks per second = 1000000000
                     Time resolution = 0x09
                     Operating system = linux
                     Number of stat entries = 0
                     Number of packets = 96
Interface #1 info:
                     Name = wlan0mon
                     Encapsulation = IEEE 802.11 plus radiotap radio header (23 - ieee-802-11-radiotap)
                     Capture length = 0
                     Time precision = nanoseconds (9)
                     Time ticks per second = 1000000000
                     Time resolution = 0x09
                     Operating system = linux
                     Number of stat entries = 0
                     Number of packets = 0
...
```

We can close this here, because the issue is related to gopacket.

**Closed by ZerBea** 2024-01-31 11:44 UTC
