### ISSUE TITLE
[hcxpcapngtool] Doesn't convert hashes as expected (proprietary macOS)

### ISSUE THREAD

**Issue by zhovner** [ZerBea/hcxtools#122] opened 2020-01-04 00:56 UTC
I would like to add hcxtools in macOS package manager Homebrew. 
Currently `hcxpcapngtool` is failed to build. Errors is trivial and can be easily fixed, but my C skills is so poor, so I'm afraid to suggest anything here  

```
$ make
mkdir -p .deps
cc -O3 -Wall -Wextra -std=gnu99 -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include  -MMD -MF .deps/hcxpcapngtool.d -o hcxpcapngtool hcxpcapngtool.c -lz -lcrypto
hcxpcapngtool.c:23:9: warning: 'PATH_MAX' macro redefined [-Wmacro-redefined]
#define PATH_MAX 255
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/syslimits.h:91:9: note: previous definition is here
#define PATH_MAX                 1024   /* max bytes in pathname */
        ^
hcxpcapngtool.c:370:77: error: expected ')'
if(eaptimegapmax > 0)                   printf("EAPOLTIME (measured maximum usec)......: %" PRId64 "\n", eaptimegapmax);
                                                                                            ^
hcxpcapngtool.c:370:31: note: to match this '('
if(eaptimegapmax > 0)                   printf("EAPOLTIME (measured maximum usec)......: %" PRId64 "\n", eaptimegapmax);
                                              ^
hcxpcapngtool.c:1169:6: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
rc = be64toh(wpak->replaycount);
     ^
hcxpcapngtool.c:1240:6: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
rc = be64toh(wpak->replaycount);
     ^
hcxpcapngtool.c:1309:6: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
rc = be64toh(wpak->replaycount);
     ^
hcxpcapngtool.c:1370:6: warning: implicit declaration of function 'be64toh' is invalid in C99 [-Wimplicit-function-declaration]
rc = be64toh(wpak->replaycount);
     ^
hcxpcapngtool.c:2122:11: warning: implicit declaration of function 'le16toh' is invalid in C99 [-Wimplicit-function-declaration]
        rthlen = le16toh(rth->it_len);
                 ^
hcxpcapngtool.c:2798:48: error: expected ')'
        "REPLAYCOUNT............................: %"  PRIu64  "\n"
                                                      ^
hcxpcapngtool.c:2787:7: note: to match this '('
printf("\nsummary capture file\n"
      ^
hcxpcapngtool.c:2517:34: warning: unused parameter 'pcaporgname' [-Wunused-parameter]
void processpcapng(int fd, char *pcaporgname, char *pcapinname)
                                 ^
7 warnings and 2 errors generated.
make: *** [hcxpcapngtool] Error 1
```

**Comment by rsumner868** [comment] 2020-01-04 06:31
```
```

```
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ZerBea** [comment] 2020-01-04 09:51
I don't have an APPLE, so we have to trial and error here.
Please test latest commit:
https://github.com/ZerBea/hcxtools/commit/c968b79f5e4263ccd3c0baa4587bb1cb90c6f6d8

**Comment by zhovner** [comment] 2020-01-04 13:03
Everything builds now, only few warnings left:

```
hcxpcapngtool.c:228:20: warning: unused function 'debugprint' [-Wunused-function]
static inline void debugprint(int len, uint8_t *ptr)
                   ^
1 warning generated.


hcxhashtool.c:218:5: warning: comparison of array 'groupoutname' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if(groupoutname != NULL)
           ^~~~~~~~~~~~    ~~~~
1 warning generated.


hcxpcaptool.c:21:9: warning: 'PATH_MAX' macro redefined [-Wmacro-redefined]
#define PATH_MAX 255
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/syslimits.h:91:9: note: previous definition is here
#define PATH_MAX                 1024   /* max bytes in pathname */
        ^
1 warning generated.
```

**Comment by ZerBea** [comment] 2020-01-04 13:19
Please try latest commit.

BTW:
hcxhashtool is in an early stage. It will work on new hashline (PMKID&EAPOL) and new potfile format.
Latest hashcat is ready for this new fomat:
$ hashcat -V
v5.1.0-1547-g8e0f976c

JtR will follow, soon:
https://github.com/magnumripper/JohnTheRipper/issues/4183

Read more about this new hash mode, here:
https://github.com/hashcat/hashcat/issues/1816

We are going to replace 1680x and 250x (hccapx) completely (R.I.P).

**Comment by ZerBea** [comment] 2020-01-04 13:21
BTW:
hcxpcapngtool.c:228:20: warning: unused function 'debugprint' [-Wunused-function]
static inline void debugprint(int len, uint8_t *ptr)

This warning is ok, because I need it for testing purpose. I remove it on final release.

**Comment by zhovner** [comment] 2020-01-04 13:52
Now builds without warnings. Great, thank you!

I've started to write a homebrew build script here [hcxtools.rb](https://github.com/zhovner/homebrew-zhovner/blob/master/hcxtools.rb). After release of hcxtools will be ready we can suggest it official repo, so macOS users can just type `brew install hcxtools`.

For those who wanna test it right now:
`brew install --head https://raw.githubusercontent.com/zhovner/homebrew-zhovner/master/hcxtools.rb`

**Comment by zhovner** [comment] 2020-01-04 14:05
Btw, when i copied a project description i notice that its "Portable solution for **CAPTURING** wlan traffic and conversion". As I understand correctly, all capturing features moved to `hcxdumptool` repo. So maybe it's time to change description?

**Comment by ZerBea** [comment] 2020-01-04 14:49
Fixed that, too. Thanks.

**Comment by ZerBea** [comment] 2020-01-05 22:14
Looks like we are running into an endianess issue on macos.

**Comment by ZerBea** [comment] 2020-01-05 22:29
Please try latest commit.

**Comment by zhovner** [comment] 2020-01-05 22:39
Absolutely same behavior:

`hcxpcapngtool -o test.22000 your-pcap-example.pcap` — not create test.22000 file and WPA*02* blindness in my bettercap dump.

**Comment by ZerBea** [comment] 2020-01-05 22:47
Ok, than it isn't related to endianess.

**Comment by ZerBea** [comment] 2020-01-06 08:52
Maybe an Appel user has a solution for this issue. I can't reproduce it, because it doesn't appear on my Linux systems.

**Comment by ZerBea** [comment] 2020-01-06 21:11
That was really bad and related to this:
https://stackoverflow.com/questions/50110709/unexplainable-difference-in-qsort-results-under-macos-and-linux
But it should be fixed, now - even though I can't explain, why.

**Closed** 2020-01-06 22:15 UTC

**Comment by magnumripper** [comment] 2020-01-11 22:05
I believe it's not so much about "Apple" but "BSD" (think FreeBSD/OpenBSD/NetBSD) - so it's not a proprietary or closed-source problem, just an incompatibility.
