### ISSUE TITLE
hcxptools seems to break wifite

### ISSUE THREAD

**Issue by zwt2135** [ZerBea/hcxtools#94] opened 2019-06-01 09:01 UTC
I am using the most recent nightly kernal 19.3 on net hunter nexus 6 android marshmallow. I can get wifite working find except when I install hcxptools. I have installed from apt install as well as direct git clone.

The issue comes after hcxptools is installed it puts wifite in a loop of deauthing a client and listening. I can never see any clients on the network even thought I know there are. It also never captures a handshake. However when I uninstall hcxptools wifite works fine. Any idea how to resolve this as I would like to be able to capture pmkids.

**Comment by ZerBea** [comment] 2019-06-01 09:32
Looks like WiFite starts hcxpcaptool again, again and again.

Please post output of
$ iw dev
$ hcxdumptool -I

So we make sure that:
the interface exists and
that the interface is set to monitor mode

**Comment by ZerBea** [comment] 2019-06-01 09:34
Also try:
$ hcxdumptool -i "your interface" --enable_status=1 -o test.pcapng
without wifite running.

**Comment by zwt2135** [comment] 2019-06-01 09:43
Thanks for the quick response I have entered in the commands and the screens shots below are the output.

![Screenshot_20190601-043850](https://user-images.githubusercontent.com/30997462/58746772-d2fe8f80-8427-11e9-91f1-014e74cec49c.png)

![Screenshot_20190601-043804](https://user-images.githubusercontent.com/30997462/58746775-d4c85300-8427-11e9-88b1-f6a9ad8659d5.png)

**Comment by ZerBea** [comment] 2019-06-01 09:45
and hcxdumptool -I ??

**Comment by ZerBea** [comment] 2019-06-01 09:50
From the output of iw dev:
you created an airmon-ng monitor interface: wlan1mon
That will not(!) work. From --help:
do not run hcxdumptool on logical interfaces (monx, wlanxmon)
do not use hcxdumptool in combination with other 3rd party tools, which take access to the interface

**Comment by zwt2135** [comment] 2019-06-01 09:54
Ok my mistake I thought you wanted to check if it was in monitor mode. However Wifite automatically uses hcxdumptool and hcxptool to do things such as pmkid attacks. When I install hcxptool it make wifite constantly loop deauthing and listening. hcxdumptool doesnt seem to be a problem more so hcxptool is causing the issues.

**Comment by ZerBea** [comment] 2019-06-01 09:55
There is no()!) hcxptool !!!!!

**Comment by ZerBea** [comment] 2019-06-01 09:56
We have hcxdumptool (attack / captureing) and hcxpcaptool (conversion).

**Comment by ZerBea** [comment] 2019-06-01 09:57
It look like wifite checks output of hcxpcaptool. If it is empty (because no handshake or PMKID was captured) wifite enters the loop again.
You should report this issue on wifite2 git, too.

**Comment by ZerBea** [comment] 2019-06-01 09:59
> Ok my mistake I thought you wanted to check if it was in monitor mode.
No, I wanted to check that hcxdumptool detects the hardware interface, or not.
Result of iw shows only an airodump-ng wlanxmon interface, but unfortunately no hardware interface.

**Comment by zwt2135** [comment] 2019-06-01 10:02
Yea I have contacted them as well I figured it was more an issue with wifite than with hcxptool. I thought i might as well make you aware of it as well but figured it was wifites issue really.

**Comment by ZerBea** [comment] 2019-06-01 10:02
Good.

**Comment by ZerBea** [comment] 2019-06-01 10:11
Running both tools on Arch, everything is fine:
https://github.com/ZerBea/hcxtools/issues/92#issuecomment-497603848
while many third party tools really cause trouble.

hcxdumptool claim to be fast. But that does not work in combination with wrappers or third party tools.
In order to accept no compromise in either speed or or ancient formats, I don't support wrappers or third party tools.

**Comment by ZerBea** [comment] 2019-06-01 10:12
Is hcxpcaptool working stand alone on your device?

**Comment by ZerBea** [comment] 2019-06-01 10:14
To test this, just copy a cap file to your device and run
$ hcxpcaptool -V "your cap file"
if that worked, we can assume wifite causes the loop.

**Comment by ZerBea** [comment] 2019-06-01 16:46
Let's do a reference to wifite:
https://github.com/derv82/wifite/issues/142
But I don't think it's the right place to inform the wifite team. Better to use wifite2 instead of wifite:
https://github.com/derv82/wifite2

**Comment by ZerBea** [comment] 2019-07-05 16:54
Is hcxpcaptool still breaking wifit2?
As a result of this issue report:
https://github.com/ZerBea/hcxtools/issues/98
I made several fixes (crashes and infinity loops) in case of damaged cap files and/or damaged ESSIDs.

**Comment by zwt2135** [comment] 2019-07-05 22:56
> 
> 
> Is hcxpcaptool still breaking wifit2?
> As a result of this issue report:
> #98
> I made several fixes (crashes and infinity loops) in case of damaged cap files and/or damaged ESSIDs.

Hey I haven't checked since I posted about it. I will install the new version and try it right now and get back to you.

**Comment by zwt2135** [comment] 2019-07-06 01:22
I have run multiple tests and it still seems that the same issue is occurring. Any time hcxtools is installed it throws wifite2 into a constant loop of deauthing and listening and never able to capture either a handshake or a pmkid. As soon as I remove hcxtools I can capture handshakes immediately.

**Comment by ZerBea** [comment] 2019-07-06 07:28
I that working:
$ hcxpcaptool -V "your cap file"
Which tool is used to request and capture pmkids/handshakes?

**Comment by ZerBea** [comment] 2019-07-06 07:38
It looks like the attack too for capturing handshakes and requesting PMKIDs doesn't work like expected. There are no handshakes/PMKIDs to convert and wifite starts the tools again.
Please check the tool for capturing and requesting PMKIDs. Output of this tool should be a cap file. Also check the cap file with wireshark for EAPOL messages.

**Comment by ZerBea** [comment] 2019-08-03 13:37
I took a look into wifite code pmkid.py and noticed that the loop is wanted by wifite:

Within lines 113 - 140 hcxpcaptool is repeatedly started:

        # Start hcxdumptool
        t = Thread(target=self.dumptool_thread)
        t.start()

        # Repeatedly run pcaptool & check output for hash for self.target.essid

Closed this issue, because it isn't caused by hcxpcaptool.

**Closed by ZerBea** 2019-08-03 13:37 UTC

**Comment by ZerBea** [comment] 2019-10-31 11:15
Just a small notice: There is work in progress. Please read more here:
https://github.com/kimocoder/wifite2/issues/1#issuecomment-548119610
