### ISSUE TITLE
complete handshake

### ISSUE THREAD

**Issue by LLH-l** [ZerBea/hcxtools#243] opened 2023-02-09 10:14 UTC
These files capture the full handshake data
But hcxpcapngtool can't recognize them, I want to know what causes  ,Thanks
still have a few questions
1. Is it because they cannot calculate the correct EAPOL value?
2. Are they never able to recover the correct password ?
3. Are there any misjudgments in these files? Or is it basically confirmed that they are unrecoverable correct passwords ?

Take a simple handshake file as an example
 Message pairs Valid EAPOL values are

1_(6401).cap
`0103007302010a00000000000000000001d30886c749369cd5ff24f2a3f5d288312b405e7fa16e748d575cca5b4d0a60e9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001430120100000fac040100000fac040100000fac02
`

1_(5272).cap
`010300ef02010b000000000000000000016c6275f44abe3b40944e5330b59a4aba6e09ece24d8b1cf9c6d7ccd30f7837a6000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009030260100000fac040100000fac040100000fac04000001008e2617e3b181af3b2f3a1976531bea693603fd27003761000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000106b83a082ab7ea03053330363834`

[test.zip](https://github.com/ZerBea/hcxtools/files/10695886/test.zip)

According to the WPA standard protocol, as long as the m2m3 message pair is included, it can be regarded as valid, and the correct password can be successfully recovered

**Comment by ZerBea** [comment] 2023-02-09 12:31
I try to explain it. We use this dump file as example: 1_(558).cap
There is a full 4way handshake inside:
packet 1100 = M1
packet 1111 = M2
packet 1114 = M3
packet 1118 = M4

Unfortunately this is not(!) a WPA PSK handshake. Hascat is not able to recover the used key from this kind of handshake.
Take a look at packet 1096 ASSOCIATIONREQUEST of the CLIENT:
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 20
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) TKIP
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
    Auth Key Management (AKM) Suite Count: 1
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) FT using PSK
    RSN Capabilities: 0x000c
```
Key management is "FT using PSK" and hcxpcapngtool show that:
ASSOCIATIONREQUEST (FT using PSK)........: 1

With packet 1098 the AP confirmed that the following 4wayhandshake is a FT unsing PSK handshake.

For example this is an ASSOCIATIONREQUEST using "PSK" looks like this:
```
Tag: RSN Information
    Tag Number: RSN Information (48)
    Tag length: 20
    RSN Version: 1
    Group Cipher Suite: 00:0f:ac (Ieee 802.11) TKIP
    Pairwise Cipher Suite Count: 1
    Pairwise Cipher Suite List 00:0f:ac (Ieee 802.11) AES (CCM)
    Auth Key Management (AKM) Suite Count: 1
    Auth Key Management (AKM) List 00:0f:ac (Ieee 802.11) PSK
    RSN Capabilities: 0x0000
```

This is an overview of CIPHER SUITES:
```
CS_WEP40
CS_TKIP
CS_WRAP
CS_CCMP
CS_WEP104
CS_BIP
```

and AUTHENTICATION KEY MANAGEMENT SUITES:
```
AK_PMKSA
AK_PSK
AK_FT
AK_FT_PSK
AK_PMKSA256
AK_PSKSHA256
AK_TDLS
AK_SAE_SHA256
AK_FT_SAE
```

More information about AUTHENTICATION, CIPHER and AKM is here:
https://mrncciew.com/2014/08/21/cwsp-rsn-information-elements/

Hashcat is able to recover the PSK from CS_TKIP and CS_CCMP in combination with AK_PSK or AK_PSKSHA256, but not from teh other ones (e.g. FT_PSK).
If you would like to recover the PSKs from "FT using PSK" I suggest to add a feature request to hashcat git.

Closed this because this behavior is wanted and not a bug.

If you have more questions, about CIPHER SUITES and AKM SUITES feel free to open a discussion here:
https://github.com/ZerBea/hcxdumptool/discussions

**Closed by ZerBea** 2023-02-09 12:31 UTC

**Comment by ZerBea** [comment] 2023-02-09 12:34
Please read this here, too:
https://github.com/aircrack-ng/aircrack-ng/issues/2197#issuecomment-1197711252

**Comment by ZerBea** [comment] 2023-02-09 12:41
Luckily the example dump file contain important frames like ASSICIATIONREQUEST and ASSOCIATIONRESPONSE frames.
If they are missing and the AP announce more than one supported AKM/CIPHERSUITE in its BEACON it would lead we never get an information about the kind of the captured 4way handshake. I've seen dump files that have only
```
one BEACON
one M1
one M2
one M3
one M4
```
inside. That is not enough and hcxdumptool show a warning that important frames are missing.

**Comment by ZerBea** [comment] 2023-02-09 12:44
We talked about EPAOL 4way handshakes, but the same applies to PMKIDs, too. You need an information about AKM and CIPHER SUITE!

**Comment by LLH-l** [comment] 2023-02-10 00:41
Good ,  thanks

**Comment by LLH-l** [comment] 2023-02-10 05:01
@ZerBea 
1_(6401).cap  What's the problem
It seems to capture complete data

**Comment by ZerBea** [comment] 2023-02-10 06:02
In 1_(6401).cap is only one EAPOL M2 and that one is damaged:
`102585	12:45:47,118269	60:21:01:0a:b4:9b	cc:08:fb:3e:ab:81	EAPOL	153	Key (Message 2 of 4)[Malformed Packet]`
hcxpcapngtool ignore damaged frames.

**Comment by LLH-l** [comment] 2023-02-10 07:46
Thanks
